Develop
NubeIO/module-core-system pull request #1
Opened 2023-06-10 15:57 UTC by maharjanaman

2023-06-15 16:36 UTC, RaiBnod commented on go.mod
> +replace github.com/NubeIO/rubix-os => /Users/i8e4/CodeDuo/NubeIO/rubix-os
Put this line at first, so we get the first insight of the package replacement.

2023-06-15 16:40 UTC, RaiBnod commented on logger/logger.go
> +}
Implement this `logLevel` on the basis of config.

2023-06-15 16:44 UTC, RaiBnod commented on pkg/schedule.go
> +
These `log.Info`s needs to be in `log.Debug` level. It's just printing so many logs. Compare with the existing plugin.

2023-06-15 16:44 UTC, RaiBnod requested changes
See those change requests.

2023-06-16 05:57 UTC, maharjanaman commented on pkg/schedule.go
> +
So we just change `Info` to `Debug` or remove it all together?

2023-06-16 06:03 UTC, RaiBnod commented on pkg/schedule.go
> +
Change into `Debug` and that level of the log needs to be customized from the config.

2023-06-18 16:26 UTC, merged